[options]
addons_path = D:\odoo-pet-project\odoo\addons,D:\odoo-pet-project\custom_addons
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
xmlrpc_port = 8069
admin_passwd = $pbkdf2-sha512$600000$D2EsReh9b60VwpiTktIaIw$77u54EonCFvM64LUeIq3dFf9DrGqrZTm2yN5fGNZp0ELVkXwlxByXKjMbav4PMUPtgjWSRyhf0jxFa4XVh4rZw

